helmDefaults:
  timeout: 30

releases:
  # backend database

  - name: backend-postgres
    chart: charts/backend-postgres
    values:
      - charts/global-values.yaml

  # client group

  - name: client
    chart: charts/client
    labels:
      clientGroup: "true"
    values:
      - charts/global-values.yaml
      - charts/values-secret.yaml

  - name: prometheus
    chart: prometheus-community/prometheus
    values:
      - charts/values-prometheus.yaml
    labels:
      clientGroup: "true"

  - name: grafana
    chart: grafana/grafana
    values:
      - charts/values-grafana.yaml
    labels:
      clientGroup: "true"
    hooks:
      - events: ["presync"]
        command: "kubectl"
        args: [
          "create",
          "configmap",
          "node-metrics-dashboard",
          "--from-file=charts/client/dashboards/node-metrics-dashboard.json"
        ]

  # application group

  - name: jooby-nomvc-app
    chart: charts/app1
    installed: false
    labels:
      appGroup: "true"

  - name: jooby-r2dbc-app
    chart: charts/app2
    installed: false
    labels:
      appGroup: "true"

  - name: jooby-vertx-app
    chart: charts/app2
    installed: false
    labels:
      appGroup: "true"

  - name: spring-async-app
    chart: charts/app2
    installed: false
    labels:
      appGroup: "true"

  - name: spring-jdbc-kernel-app
    chart: charts/spring-jdbc-app
    installed: {{ .Values | getOrNil "spring-jdbc-kernel-app_installed" | default false }}
    labels:
      appGroup: "true"
    values:
      - charts/global-values.yaml
      - charts/values-secret.yaml
      - spring:
          threads:
            virtual:
              enabled: "false"

  - name: spring-jdbc-virtual-app
    chart: charts/spring-jdbc-app
    installed: {{ .Values | getOrNil "spring-jdbc-virtual-app_installed" | default false }}
    labels:
      appGroup: "true"
    values:
      - charts/global-values.yaml
      - charts/values-secret.yaml
      - spring:
          threads:
            virtual:
              enabled: "true"

  - name: spring-webflux-app
    chart: charts/app2
    installed: false
    labels:
      appGroup: "true"
