environments:
  default:
    values:
      # provides the global values to templates in this helmfile
      - charts/global-values.yaml

---

helmDefaults:
  timeout: 30

releases:
  # backend database

  - name: backend-postgres
    chart: charts/backend-postgres
    values:
      - charts/global-values.yaml

  # client group

  - name: client
    chart: charts/client
    labels:
      clientGroup: "true"
    values:
      - charts/global-values.yaml
      - charts/values-secret.yaml

  - name: prometheus
    chart: prometheus-community/prometheus
    values:
      - charts/values-prometheus.yaml
    labels:
      clientGroup: "true"

  - name: grafana
    chart: grafana/grafana
    values:
      - charts/values-grafana.yaml
    labels:
      clientGroup: "true"
    hooks:
      - events: ["presync", "postuninstall"]
        command: "kubectl"
        args: [
          "delete",
          "configmap",
          "node-metrics-dashboard"
        ]
      - events: ["presync"]
        command: "kubectl"
        args: [
          "create",
          "configmap",
          "node-metrics-dashboard",
          "--from-file=charts/client/dashboards/node-metrics-dashboard.json"
        ]

  # application group

  - name: jooby-nomvc-app
    chart: charts/generic-app
    installed: {{ .Values | getOrNil "jooby-nomvc-app_installed" | default false }}
    labels:
      appGroup: "true"
    values:
      - charts/global-values.yaml
      - charts/values-secret.yaml
      - env:
          SERVER_PORT: "{{ .Values.global.app.port }}"
          DATABASE_URL: "jdbc:{{ .Values.global.pgbouncer.host }}"
          DATABASE_USERNAME: "{{ .Values.global.database.username }}"
          DATABASE_PASSWORD: "{{ .Values.global.database.password }}"

  - name: jooby-r2dbc-app
    chart: charts/generic-app
    installed: {{ .Values | getOrNil "jooby-r2dbc-app_installed" | default false }}
    labels:
      appGroup: "true"
    values:
      - charts/global-values.yaml
      - charts/values-secret.yaml
      - env:
          SERVER_PORT: "{{ .Values.global.app.port }}"
          DATABASE_HOST_NAME: "{{ .Values.global.pgbouncer.hostName }}"
          DATABASE_PORT: "{{ .Values.global.pgbouncer.port }}"
          DATABASE_NAME: "{{ .Values.global.database.name }}"
          DATABASE_USERNAME: "{{ .Values.global.database.username }}"
          DATABASE_PASSWORD: "{{ .Values.global.database.password }}"

  - name: jooby-vertx-app
    chart: charts/generic-app
    installed: {{ .Values | getOrNil "jooby-vertx-app_installed" | default false }}
    labels:
      appGroup: "true"
    values:
      - charts/global-values.yaml
      - charts/values-secret.yaml
      - env:
          SERVER_PORT: "{{ .Values.global.app.port }}"
          DATABASE_HOST_NAME: "{{ .Values.global.pgbouncer.hostName }}"
          DATABASE_PORT: "{{ .Values.global.pgbouncer.port }}"
          DATABASE_NAME: "{{ .Values.global.database.name }}"
          DATABASE_USERNAME: "{{ .Values.global.database.username }}"
          DATABASE_PASSWORD: "{{ .Values.global.database.password }}"

  - name: spring-async-app
    chart: charts/generic-app
    installed: {{ .Values | getOrNil "spring-async-app_installed" | default false }}
    labels:
      appGroup: "true"
    values:
      - charts/global-values.yaml
      - charts/values-secret.yaml

  - name: spring-jdbc-kernel-app
    chart: charts/spring-jdbc-app
    installed: {{ .Values | getOrNil "spring-jdbc-kernel-app_installed" | default false }}
    labels:
      appGroup: "true"
    values:
      - charts/global-values.yaml
      - charts/values-secret.yaml
      - spring:
          threads:
            virtual:
              enabled: "false"

  - name: spring-jdbc-virtual-app
    chart: charts/spring-jdbc-app
    installed: {{ .Values | getOrNil "spring-jdbc-virtual-app_installed" | default false }}
    labels:
      appGroup: "true"
    values:
      - charts/global-values.yaml
      - charts/values-secret.yaml
      - spring:
          threads:
            virtual:
              enabled: "true"

  - name: spring-webflux-app
    chart: charts/generic-app
    installed: {{ .Values | getOrNil "spring-webflux-app_installed" | default false }}
    labels:
      appGroup: "true"
    values:
      - charts/global-values.yaml
      - charts/values-secret.yaml
      - env:
          SERVER_PORT: "{{ .Values.global.app.port }}"
          SPRING_R2DBC_URL: "r2dbc:{{ .Values.global.pgbouncer.host }}"
          SPRING_R2DBC_USERNAME: "{{ .Values.global.database.username }}"
          SPRING_R2DBC_PASSWORD: "{{ .Values.global.database.password }}"
