apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.global.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      nodeSelector:
        kubernetes.io/hostname: app
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.global.app.dockerImagePrefix }}/{{ .Release.Name }}:latest
          imagePullPolicy: {{ .Values.global.app.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.global.app.port }}
          env:
            - name: SERVER_PORT
              value: "{{ .Values.global.app.port }}"
            - name: DATABASE_HOST_NAME
              value: "{{ .Values.global.pgbouncer.hostName }}"
            - name: DATABASE_PORT
              value: "{{ .Values.global.pgbouncer.port }}"
            - name: DATABASE_NAME
              value: "{{ .Values.global.database.name }}"
            - name: DATABASE_USERNAME
              value: "{{ .Values.global.database.username }}"
            - name: DATABASE_PASSWORD
              value: "{{ .Values.global.database.password }}"
