apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.global.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      nodeSelector:
        kubernetes.io/hostname: app
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.global.app.dockerImagePrefix }}/{{ .Release.Name }}:latest
          imagePullPolicy: {{ .Values.global.app.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.global.app.port }}
